"""Telegram output (spec section 8) -- plain-English, three distinct formats.

Lead with words and a confidence number (= composite), then a compact execution
block. Every "Why today?" line is generated by a factor crossing its threshold
-- never hand-decorative. A 5/5 message therefore means five independent things
genuinely aligned. The mapping below is fixed; a line only appears when its
factor fires.

The system always sends *something*: a firing card, or the No-Trade card.
"""

from __future__ import annotations

import os
from dataclasses import dataclass

import urllib.parse
import urllib.request

from .config import PARAMS, Params
from .fire import Decision, FireResult
from .iv_store import IVStore
from .models import Candidate, MarketRegime, OptionContract
from .strike import ExitPlan


# Fixed factor -> line mapping (section 8). Each entry: (factor id, threshold,
# label-builder). "Market supportive" is keyed off the regime, not a factor.
WHY_THRESHOLD = 70.0


def _why_lines(cand: Candidate, regime: MarketRegime, store: IVStore | None) -> list[str]:
    f = cand.score.factors
    s = cand.snapshot
    lines: list[str] = []

    if f["F1"] >= WHY_THRESHOLD:
        lines.append("Trend improving")
    if f["F3"] >= WHY_THRESHOLD:
        lines.append("Pullback finished")
    if f["F2"] >= WHY_THRESHOLD:
        months = store.months_of_history(s.symbol) if store else 0
        iv_pct = f"  (IV pct {s.iv_percentile:.0f})" if s.iv_percentile is not None else ""
        if months:
            lines.append(f"Volatility lowest in {months} months{iv_pct}")
        else:
            lines.append(f"Volatility low{iv_pct}")
    if f["F5"] >= WHY_THRESHOLD:
        lines.append(_sector_line(s))
    if f["F6"] >= WHY_THRESHOLD:
        lines.append("Volume confirming")
    if regime.spy_above_50_200:
        lines.append("Market supportive")
    # Wide-open runway is a Moonshot-tier line (big runway is part of the upgrade).
    return lines


def _sector_line(s) -> str:
    spy = s.rel_strength.get("spy", {})
    sector = s.rel_strength.get("sector", {})
    detail = ""
    if 20 in sector and 20 in spy:
        detail = (f"  (leads {s.sector_etf} {sector[20]*100:+.0f}% / "
                  f"SPY {spy[20]*100:+.0f}%, 20d)")
    return f"Sector strongest{detail}"


def _runway_line(s) -> str:
    return f"Wide-open runway  ({s.atr_to_resistance:.1f} ATR to next ceiling)"


def _trade_block(contract: OptionContract) -> list[str]:
    """The execution block. Premium is shown as a fill *range*, not a single
    number -- you place a limit order, you don't fill at the theoretical mid.
    Aim for the mid; don't chase past the ask. Cost is per share; x100 = the
    cash per contract (and, for a long call, the max loss)."""
    lo, hi = PARAMS.dte_range
    per_contract = contract.mid * 100
    return [
        f"TRADE: {lo}-{hi} DTE call, ~{contract.delta:.2f} delta  (strike ${contract.strike:g})",
        f"Cost ~${contract.mid:.2f}/sh = ~${per_contract:,.0f} per contract",
        f"Limit ${contract.mid:.2f}-${contract.ask:.2f}/sh  "
        f"(aim mid, bid ${contract.bid:.2f} / ask ${contract.ask:.2f})",
        f"Breakeven ${contract.strike + contract.mid:.2f}",
    ]


# --------------------------------------------------------------------------- #
# Message builders
# --------------------------------------------------------------------------- #
def no_trade_card(fr: FireResult, scanned: int, past_gates: int) -> str:
    top = fr.top
    if top is None:
        return ("\U0001F634 No Trade Today\n"
                f"No candidate passed the gates.\nScanned {scanned} · past gates {past_gates}")
    reason = fr.block_reason or "blocked"
    return (
        "\U0001F634 No Trade Today\n"
        f"Top candidate: {top.snapshot.symbol} (confidence {top.score.composite:.0f}) "
        f"— blocked: {reason}\n"
        f"Scanned {scanned} · past gates {past_gates}"
    )


def standard_card(
    cand: Candidate, contract: OptionContract, exits: ExitPlan,
    regime: MarketRegime, store: IVStore | None,
) -> str:
    why = "\n".join(f"✓ {line}" for line in _why_lines(cand, regime, store))
    exit_line = (" · ".join(exits.lines))
    return (
        f"✅ Buy {cand.snapshot.symbol}          Confidence {cand.score.composite:.0f}/100\n\n"
        "Why today?\n"
        f"{why}\n\n"
        + "\n".join(_trade_block(contract)) + "\n"
        f"EXIT: {exit_line}"
    )


def moonshot_card(
    cand: Candidate, contract: OptionContract, exits: ExitPlan,
    regime: MarketRegime, store: IVStore | None,
) -> str:
    s = cand.snapshot
    why_lines = _why_lines(cand, regime, store)
    why_lines.append(_runway_line(s))
    why = "\n".join(f"✓ {line}" for line in why_lines)
    exit_block = "\n".join(f"  • {line}" for line in exits.lines)
    months = store.months_of_history(s.symbol) if store else 12
    return (
        f"\U0001F680\U0001F680 MOONSHOT — {s.symbol} \U0001F680\U0001F680     "
        f"Confidence {cand.score.composite:.0f}/100\n\n"
        f"⭐ THE RARE ONE: cheapest IV in {months} months, yet leading its sector "
        "AND the market.\n"
        "   Forgotten-cheap, but acting like a leader. This is the setup to attempt.\n\n"
        "Why today?\n"
        f"{why}\n\n"
        + "\n".join(_trade_block(contract)) + "\n"
        "EXIT (scale-out):\n"
        f"{exit_block}"
    )


@dataclass
class Alert:
    decision: Decision
    text: str


def entry_check_card(
    signal: dict,
    contract: OptionContract | None,
    exits: ExitPlan | None,
    gate_failed: list[str] | None,
    gap_pct: float | None,
    gap_atr: float | None,
    gap_warn: bool,
) -> str:
    """The next-morning re-validation card (~9:45 ET), sent only when the
    evening scan fired. Confirms the live trade or tells you to skip."""
    sym = signal.get("symbol")
    tier = "Moonshot" if signal.get("decision") == Decision.MOONSHOT.value else "Standard"
    head = f"\U0001F514 ENTRY CHECK — {sym} ({tier} signal from {signal.get('date')})"

    overnight = ""
    if gap_pct is not None:
        ref = signal.get("ref_close")
        spot = ref * (1 + gap_pct) if ref else None
        atr_txt = f", {gap_atr:.1f} ATR" if gap_atr is not None else ""
        spot_txt = f" (${ref:.2f} → ${spot:.2f})" if ref and spot else ""
        overnight = f"\nOvernight: {gap_pct*100:+.1f}%{atr_txt}{spot_txt}"

    # SKIP cases first
    if gate_failed:
        reason = _gate_skip_reason(gate_failed, contract)
        return f"{head}\n⚠️ SKIP — {reason}{overnight}"
    if contract is None:
        return f"{head}\n⚠️ SKIP — no tradeable strike on the live chain right now.{overnight}"
    if gap_warn:
        return (f"{head}\n⚠️ CAUTION — gapped {gap_pct*100:+.1f}% overnight; the setup "
                f"may be extended now. Re-judge before entering.{overnight}\n\n"
                + _live_trade_text(contract, exits))

    return f"{head}\n✅ STILL VALID — place it.{overnight}\n\n" + _live_trade_text(contract, exits)


def _gate_skip_reason(failed: list[str], contract: OptionContract | None) -> str:
    if "G1" in failed:
        return "trend broke overnight (gapped below EMA50/200). G1 failed."
    if "G2" in failed:
        return "gapped into a blow-off (RSI/extension). G2 failed."
    if "G4" in failed:
        if contract is not None:
            return (f"liquidity not there this morning (spread {contract.spread_pct*100:.0f}%, "
                    f"OI {contract.open_interest}, vol {contract.volume}). "
                    "G4 failed — re-check in 15 min once the book fills.")
        return "no liquid strike this morning. G4 failed."
    return f"gate(s) failed: {', '.join(failed)}."


def _live_trade_text(contract: OptionContract, exits: ExitPlan | None) -> str:
    lines = "\n".join(_trade_block(contract))
    exit_txt = ""
    if exits:
        exit_txt = "\nEXIT: " + " · ".join(exits.lines)
    return lines + exit_txt


def render(
    fr: FireResult,
    contract: OptionContract | None,
    exits: ExitPlan | None,
    regime: MarketRegime,
    scanned: int,
    past_gates: int,
    store: IVStore | None = None,
    warmup_note: str | None = None,
) -> Alert:
    if fr.decision == Decision.NO_TRADE or contract is None:
        return Alert(Decision.NO_TRADE, no_trade_card(fr, scanned, past_gates))
    if fr.decision == Decision.MOONSHOT:
        text = moonshot_card(fr.top, contract, exits, regime, store)
    else:
        text = standard_card(fr.top, contract, exits, regime, store)
    if warmup_note:
        text += f"\n\n⚠️ {warmup_note}"
    return Alert(fr.decision, text)


# --------------------------------------------------------------------------- #
# Delivery
# --------------------------------------------------------------------------- #
def send(text: str, *, token: str | None = None, chat_id: str | None = None) -> bool:
    """Send a message via the Telegram bot API. Credentials come from the
    environment (GitHub Action secrets): TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID.

    Returns True on success. If credentials are absent (local dry run), prints
    the message and returns False.
    """
    token = token or os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = chat_id or os.environ.get("TELEGRAM_CHAT_ID")
    if not token or not chat_id:
        print("[telegram: no credentials, dry run]\n" + text)
        return False

    url = f"https://api.telegram.org/bot{token}/sendMessage"
    data = urllib.parse.urlencode({"chat_id": chat_id, "text": text}).encode()
    try:
        with urllib.request.urlopen(url, data=data, timeout=30) as resp:
            return resp.status == 200
    except Exception as exc:  # noqa: BLE001 -- never let delivery crash the run
        print(f"[telegram send failed: {exc}]\n{text}")
        return False
